### PR TITLE
Quickstart fixes

### LINKED ISSUE #135: Order Quickstart by ascending order on upvotes
Right now they are ordered in descending order

### PR DESCRIPTION
**Pull request by brunnoattorre**
Fixes #135 #143

### CODE REVIEW

**Comment by callicles** [comment]
I don't think we want the ga on the dev server, it will thorw off the stats

**Comment by brunnoattorre** [comment]
Yeah, I've made the branch from master so that stuff went in. Just removed it, should be fine now.

File: public/javascripts/repository.js [hunk 1]
```diff
@@ -35,6 +35,21 @@ function buildQuickstartGuides(data) {
...
+        if (listDOM[i].nodeType === 1 && listDOM[i].getAttribute("upvote")!= null) { // get rid of the whitespace text nodes
+            list.push(listDOM[i]);
+        }
+    }
+    list.push(div)
+    list.sort(sort_by_name);
+    return list
+
+}
 function createGuideElement (guide){
```
Comment (callicles) [inline public/javascripts/repository.js]: Codacy Issue found: ['createGuideElement' is defined but never used.](https://www.codacy.com/app/gitlinks/gitrank-web/file/1338151910/issues/source?bid=2432310&fileBranchId=2964069#l53)
