### PR TITLE
Elasticsearch fix

### LINKED ISSUE #155: Search not working with dash character
Search is not working on special characters

### PR DESCRIPTION
**Pull request by brunnoattorre**
Fix #155

### CODE REVIEW

**Comment by brunnoattorre** [comment]
Fix #154

File: app/models/daos/drivers/GitHubAPI.scala [hunk 1]
```diff
@@ -35,25 +35,40 @@ class GitHubAPI @Inject()(ws: WSClient, oauthDAO: OAuth2InfoDAO) {
...
+          else {
+            Future(None)
+          }
+        }
+        case HttpStatus.SC_OK => {
+          val userContribution = response.json.as[JsArray].value
+            .filter(contributor => (contributor \ "author" \ "login").as[String] == user.username)
+          userContribution.length match {
+            case 0 => Future(None)
+            case 1 => Future(Some((userContribution.head \ "weeks").as[JsArray].value.foldRight(Contribution(0, 0, 0, None)) {
```
Comment (callicles) [inline app/models/daos/drivers/GitHubAPI.scala]: Codacy Issue found: [Usage of head on collections.](https://www.codacy.com/app/gitlinks/gitrank-web/file/1553818054/issues/source?bid=2432310&fileBranchId=3016065#l58)

File: app/models/daos/drivers/GitHubAPI.scala [hunk 2]
```diff
@@ -35,25 +35,39 @@ class GitHubAPI @Inject()(ws: WSClient, oauthDAO: OAuth2InfoDAO) {
...
+          else {
+            Future.successful(None)
+          }
+        }
+        case HttpStatus.SC_OK => {
+          val userContribution = response.json.as[JsArray].value
+            .filter(contributor => (contributor \ "author" \ "login").as[String] == user.username)
+          userContribution.length match {
+            case 0 => Future.successful(None)
+            case 1 => Future.successful(Some((userContribution.head \ "weeks").as[JsArray].value.foldRight(Contribution(0, 0, 0, None)) {
```
Comment (callicles) [inline app/models/daos/drivers/GitHubAPI.scala]: Codacy Issue found: [Usage of head on collections.](https://www.codacy.com/app/gitlinks/gitrank-web/file/1553976527/issues/source?bid=2432310&fileBranchId=3016065#l57)
